"""Shared SQLAlchemy models + session helpers.

PostgreSQL is the source of truth. The uniqueness and check constraints that
protect the invariants live in :mod:`protrix_contracts.db.models` and are created
by Alembic - not merely asserted in application code.
"""

from protrix_contracts.db.base import Base, metadata
from protrix_contracts.db.models import (
    AccountCategory,
    AccountTransport,
    AuditEvent,
    ClosedTradeAttribution,
    EnrollmentAccount,
    EnrollmentStatus,
    EscrowLedgerEntry,
    Execution,
    ManagedPosition,
    ManagedPositionStatus,
    MockBrokerDeal,
    OrderIntent,
    Outbox,
    OutboxStatus,
    PaymentEvent,
    PaymentOrder,
    PaymentPurpose,
    PaymentStatus,
    PurchaseSource,
    RentLedgerEntry,
    RentLedgerEntryType,
    RiskProfile,
    Settlement,
    SettlementCadence,
    Signal,
    Strategy,
    StrategyAssignment,
    StrategyEnrollment,
    StrategyOffer,
    StrategyPurchase,
    StrategySettlement,
    Subscription,
    SubscriptionStatus,
    TradingAccount,
    TradingAccountStatus,
    TradingControl,
    User,
    UserRole,
)
from protrix_contracts.db.session import (
    build_engine,
    build_session_factory,
    session_scope,
)

__all__ = [
    "Base",
    "metadata",
    "User",
    "UserRole",
    "TradingAccount",
    "TradingAccountStatus",
    "AccountCategory",
    "AccountTransport",
    "EnrollmentStatus",
    "Subscription",
    "SubscriptionStatus",
    "TradingControl",
    "RiskProfile",
    "ManagedPosition",
    "ManagedPositionStatus",
    "Strategy",
    "StrategyOffer",
    "StrategyEnrollment",
    "EnrollmentAccount",
    "StrategyPurchase",
    "PaymentOrder",
    "PaymentEvent",
    "PaymentPurpose",
    "PaymentStatus",
    "PurchaseSource",
    "EscrowLedgerEntry",
    "ClosedTradeAttribution",
    "StrategySettlement",
    "StrategyAssignment",
    "Signal",
    "Outbox",
    "OutboxStatus",
    "OrderIntent",
    "Execution",
    "AuditEvent",
    "MockBrokerDeal",
    "Settlement",
    "SettlementCadence",
    "RentLedgerEntry",
    "RentLedgerEntryType",
    "build_engine",
    "build_session_factory",
    "session_scope",
]
